TrajectoryPlannerROS:
  max_vel_x: 0.3
  min_vel_x: 0.05
  max_vel_theta: 1.5
  min_in_place_vel_theta: 0.1

  acc_lim_theta: 1.5
  acc_lim_x: 0.07
  acc_lim_y: 0.07
  meter_scoring: true
  planner_frequency: 5
  pdist_scale: 2
  occdist_scale: 5
  gdist_scale: 4
  heading_lookahead: 5
  dwa: false

  
  

  holonomic_robot: false  
