//#line 2 "/opt/ros/kinetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"
// *********************************************************
//
// File autogenerated for the teraranger_mutliflex_cfg package
// by the dynamic_reconfigure package.
// Please do not edit.
//
// ********************************************************/

#ifndef __teraranger_mutliflex_cfg__TERARANGERHUBMULTIFLEXCONFIG_H__
#define __teraranger_mutliflex_cfg__TERARANGERHUBMULTIFLEXCONFIG_H__

#if __cplusplus >= 201103L
#define DYNAMIC_RECONFIGURE_FINAL final
#else
#define DYNAMIC_RECONFIGURE_FINAL
#endif

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/Group.h>
#include <dynamic_reconfigure/config_init_mutex.h>
#include <boost/any.hpp>

namespace teraranger_mutliflex_cfg
{
  class TerarangerHubMultiflexConfigStatics;

  class TerarangerHubMultiflexConfig
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l,
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }

      virtual void clamp(TerarangerHubMultiflexConfig &config, const TerarangerHubMultiflexConfig &max, const TerarangerHubMultiflexConfig &min) const = 0;
      virtual void calcLevel(uint32_t &level, const TerarangerHubMultiflexConfig &config1, const TerarangerHubMultiflexConfig &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, TerarangerHubMultiflexConfig &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const TerarangerHubMultiflexConfig &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, TerarangerHubMultiflexConfig &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const TerarangerHubMultiflexConfig &config) const = 0;
      virtual void getValue(const TerarangerHubMultiflexConfig &config, boost::any &val) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template <class T>
    class ParamDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string a_name, std::string a_type, uint32_t a_level,
          std::string a_description, std::string a_edit_method, T TerarangerHubMultiflexConfig::* a_f) :
        AbstractParamDescription(a_name, a_type, a_level, a_description, a_edit_method),
        field(a_f)
      {}

      T (TerarangerHubMultiflexConfig::* field);

      virtual void clamp(TerarangerHubMultiflexConfig &config, const TerarangerHubMultiflexConfig &max, const TerarangerHubMultiflexConfig &min) const
      {
        if (config.*field > max.*field)
          config.*field = max.*field;

        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const TerarangerHubMultiflexConfig &config1, const TerarangerHubMultiflexConfig &config2) const
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, TerarangerHubMultiflexConfig &config) const
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const TerarangerHubMultiflexConfig &config) const
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, TerarangerHubMultiflexConfig &config) const
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const TerarangerHubMultiflexConfig &config) const
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }

      virtual void getValue(const TerarangerHubMultiflexConfig &config, boost::any &val) const
      {
        val = config.*field;
      }
    };

    class AbstractGroupDescription : public dynamic_reconfigure::Group
    {
      public:
      AbstractGroupDescription(std::string n, std::string t, int p, int i, bool s)
      {
        name = n;
        type = t;
        parent = p;
        state = s;
        id = i;
      }

      std::vector<AbstractParamDescriptionConstPtr> abstract_parameters;
      bool state;

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &config) const =0;
      virtual void updateParams(boost::any &cfg, TerarangerHubMultiflexConfig &top) const= 0;
      virtual void setInitialState(boost::any &cfg) const = 0;


      void convertParams()
      {
        for(std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = abstract_parameters.begin(); i != abstract_parameters.end(); ++i)
        {
          parameters.push_back(dynamic_reconfigure::ParamDescription(**i));
        }
      }
    };

    typedef boost::shared_ptr<AbstractGroupDescription> AbstractGroupDescriptionPtr;
    typedef boost::shared_ptr<const AbstractGroupDescription> AbstractGroupDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template<class T, class PT>
    class GroupDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractGroupDescription
    {
    public:
      GroupDescription(std::string a_name, std::string a_type, int a_parent, int a_id, bool a_s, T PT::* a_f) : AbstractGroupDescription(a_name, a_type, a_parent, a_id, a_s), field(a_f)
      {
      }

      GroupDescription(const GroupDescription<T, PT>& g): AbstractGroupDescription(g.name, g.type, g.parent, g.id, g.state), field(g.field), groups(g.groups)
      {
        parameters = g.parameters;
        abstract_parameters = g.abstract_parameters;
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        if(!dynamic_reconfigure::ConfigTools::getGroupState(msg, name, (*config).*field))
          return false;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          if(!(*i)->fromMessage(msg, n))
            return false;
        }

        return true;
      }

      virtual void setInitialState(boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        T* group = &((*config).*field);
        group->state = state;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = boost::any(&((*config).*field));
          (*i)->setInitialState(n);
        }

      }

      virtual void updateParams(boost::any &cfg, TerarangerHubMultiflexConfig &top) const
      {
        PT* config = boost::any_cast<PT*>(cfg);

        T* f = &((*config).*field);
        f->setParams(top, abstract_parameters);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          (*i)->updateParams(n, top);
        }
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &cfg) const
      {
        const PT config = boost::any_cast<PT>(cfg);
        dynamic_reconfigure::ConfigTools::appendGroup<T>(msg, name, id, parent, config.*field);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          (*i)->toMessage(msg, config.*field);
        }
      }

      T (PT::* field);
      std::vector<TerarangerHubMultiflexConfig::AbstractGroupDescriptionConstPtr> groups;
    };

class DEFAULT
{
  public:
    DEFAULT()
    {
      state = true;
      name = "Default";
    }

    void setParams(TerarangerHubMultiflexConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("Sensor_0"==(*_i)->name){Sensor_0 = boost::any_cast<bool>(val);}
        if("Sensor_1"==(*_i)->name){Sensor_1 = boost::any_cast<bool>(val);}
        if("Sensor_2"==(*_i)->name){Sensor_2 = boost::any_cast<bool>(val);}
        if("Sensor_3"==(*_i)->name){Sensor_3 = boost::any_cast<bool>(val);}
        if("Sensor_4"==(*_i)->name){Sensor_4 = boost::any_cast<bool>(val);}
        if("Sensor_5"==(*_i)->name){Sensor_5 = boost::any_cast<bool>(val);}
        if("Sensor_6"==(*_i)->name){Sensor_6 = boost::any_cast<bool>(val);}
        if("Sensor_7"==(*_i)->name){Sensor_7 = boost::any_cast<bool>(val);}
      }
    }

    bool Sensor_0;
bool Sensor_1;
bool Sensor_2;
bool Sensor_3;
bool Sensor_4;
bool Sensor_5;
bool Sensor_6;
bool Sensor_7;

    bool state;
    std::string name;

    
}groups;



//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      bool Sensor_0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      bool Sensor_1;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      bool Sensor_2;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      bool Sensor_3;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      bool Sensor_4;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      bool Sensor_5;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      bool Sensor_6;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      bool Sensor_7;
//#line 228 "/opt/ros/kinetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();

      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        if ((*i)->fromMessage(msg, *this))
          count++;

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i ++)
      {
        if ((*i)->id == 0)
        {
          boost::any n = boost::any(this);
          (*i)->updateParams(n, *this);
          (*i)->fromMessage(msg, n);
        }
      }

      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("TerarangerHubMultiflexConfig::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (unsigned int i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (unsigned int i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (unsigned int i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (unsigned int i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__, const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toMessage(msg, *this);

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        if((*i)->id == 0)
        {
          (*i)->toMessage(msg, *this);
        }
      }
    }

    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      __toMessage__(msg, __param_descriptions__, __group_descriptions__);
    }

    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      static bool setup=false;

      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->fromServer(nh, *this);

      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++){
        if (!setup && (*i)->id == 0) {
          setup = true;
          boost::any n = boost::any(this);
          (*i)->setInitialState(n);
        }
      }
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const TerarangerHubMultiflexConfig &__max__ = __getMax__();
      const TerarangerHubMultiflexConfig &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const TerarangerHubMultiflexConfig &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->calcLevel(level, config, *this);
      return level;
    }

    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const TerarangerHubMultiflexConfig &__getDefault__();
    static const TerarangerHubMultiflexConfig &__getMax__();
    static const TerarangerHubMultiflexConfig &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    static const std::vector<AbstractGroupDescriptionConstPtr> &__getGroupDescriptions__();

  private:
    static const TerarangerHubMultiflexConfigStatics *__get_statics__();
  };

  template <> // Max and min are ignored for strings.
  inline void TerarangerHubMultiflexConfig::ParamDescription<std::string>::clamp(TerarangerHubMultiflexConfig &config, const TerarangerHubMultiflexConfig &max, const TerarangerHubMultiflexConfig &min) const
  {
    (void) config;
    (void) min;
    (void) max;
    return;
  }

  class TerarangerHubMultiflexConfigStatics
  {
    friend class TerarangerHubMultiflexConfig;

    TerarangerHubMultiflexConfigStatics()
    {
TerarangerHubMultiflexConfig::GroupDescription<TerarangerHubMultiflexConfig::DEFAULT, TerarangerHubMultiflexConfig> Default("Default", "", 0, 0, true, &TerarangerHubMultiflexConfig::groups);
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.Sensor_0 = 0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.Sensor_0 = 1;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.Sensor_0 = 1;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(TerarangerHubMultiflexConfig::AbstractParamDescriptionConstPtr(new TerarangerHubMultiflexConfig::ParamDescription<bool>("Sensor_0", "bool", 1, "Activate sensor", "", &TerarangerHubMultiflexConfig::Sensor_0)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(TerarangerHubMultiflexConfig::AbstractParamDescriptionConstPtr(new TerarangerHubMultiflexConfig::ParamDescription<bool>("Sensor_0", "bool", 1, "Activate sensor", "", &TerarangerHubMultiflexConfig::Sensor_0)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.Sensor_1 = 0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.Sensor_1 = 1;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.Sensor_1 = 1;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(TerarangerHubMultiflexConfig::AbstractParamDescriptionConstPtr(new TerarangerHubMultiflexConfig::ParamDescription<bool>("Sensor_1", "bool", 1, "Activate sensor", "", &TerarangerHubMultiflexConfig::Sensor_1)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(TerarangerHubMultiflexConfig::AbstractParamDescriptionConstPtr(new TerarangerHubMultiflexConfig::ParamDescription<bool>("Sensor_1", "bool", 1, "Activate sensor", "", &TerarangerHubMultiflexConfig::Sensor_1)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.Sensor_2 = 0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.Sensor_2 = 1;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.Sensor_2 = 1;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(TerarangerHubMultiflexConfig::AbstractParamDescriptionConstPtr(new TerarangerHubMultiflexConfig::ParamDescription<bool>("Sensor_2", "bool", 1, "Activate sensor", "", &TerarangerHubMultiflexConfig::Sensor_2)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(TerarangerHubMultiflexConfig::AbstractParamDescriptionConstPtr(new TerarangerHubMultiflexConfig::ParamDescription<bool>("Sensor_2", "bool", 1, "Activate sensor", "", &TerarangerHubMultiflexConfig::Sensor_2)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.Sensor_3 = 0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.Sensor_3 = 1;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.Sensor_3 = 1;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(TerarangerHubMultiflexConfig::AbstractParamDescriptionConstPtr(new TerarangerHubMultiflexConfig::ParamDescription<bool>("Sensor_3", "bool", 1, "Activate sensor", "", &TerarangerHubMultiflexConfig::Sensor_3)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(TerarangerHubMultiflexConfig::AbstractParamDescriptionConstPtr(new TerarangerHubMultiflexConfig::ParamDescription<bool>("Sensor_3", "bool", 1, "Activate sensor", "", &TerarangerHubMultiflexConfig::Sensor_3)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.Sensor_4 = 0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.Sensor_4 = 1;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.Sensor_4 = 1;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(TerarangerHubMultiflexConfig::AbstractParamDescriptionConstPtr(new TerarangerHubMultiflexConfig::ParamDescription<bool>("Sensor_4", "bool", 1, "Activate sensor", "", &TerarangerHubMultiflexConfig::Sensor_4)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(TerarangerHubMultiflexConfig::AbstractParamDescriptionConstPtr(new TerarangerHubMultiflexConfig::ParamDescription<bool>("Sensor_4", "bool", 1, "Activate sensor", "", &TerarangerHubMultiflexConfig::Sensor_4)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.Sensor_5 = 0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.Sensor_5 = 1;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.Sensor_5 = 1;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(TerarangerHubMultiflexConfig::AbstractParamDescriptionConstPtr(new TerarangerHubMultiflexConfig::ParamDescription<bool>("Sensor_5", "bool", 1, "Activate sensor", "", &TerarangerHubMultiflexConfig::Sensor_5)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(TerarangerHubMultiflexConfig::AbstractParamDescriptionConstPtr(new TerarangerHubMultiflexConfig::ParamDescription<bool>("Sensor_5", "bool", 1, "Activate sensor", "", &TerarangerHubMultiflexConfig::Sensor_5)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.Sensor_6 = 0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.Sensor_6 = 1;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.Sensor_6 = 1;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(TerarangerHubMultiflexConfig::AbstractParamDescriptionConstPtr(new TerarangerHubMultiflexConfig::ParamDescription<bool>("Sensor_6", "bool", 1, "Activate sensor", "", &TerarangerHubMultiflexConfig::Sensor_6)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(TerarangerHubMultiflexConfig::AbstractParamDescriptionConstPtr(new TerarangerHubMultiflexConfig::ParamDescription<bool>("Sensor_6", "bool", 1, "Activate sensor", "", &TerarangerHubMultiflexConfig::Sensor_6)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.Sensor_7 = 0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.Sensor_7 = 1;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.Sensor_7 = 1;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(TerarangerHubMultiflexConfig::AbstractParamDescriptionConstPtr(new TerarangerHubMultiflexConfig::ParamDescription<bool>("Sensor_7", "bool", 1, "Activate sensor", "", &TerarangerHubMultiflexConfig::Sensor_7)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(TerarangerHubMultiflexConfig::AbstractParamDescriptionConstPtr(new TerarangerHubMultiflexConfig::ParamDescription<bool>("Sensor_7", "bool", 1, "Activate sensor", "", &TerarangerHubMultiflexConfig::Sensor_7)));
//#line 245 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.convertParams();
//#line 245 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(TerarangerHubMultiflexConfig::AbstractGroupDescriptionConstPtr(new TerarangerHubMultiflexConfig::GroupDescription<TerarangerHubMultiflexConfig::DEFAULT, TerarangerHubMultiflexConfig>(Default)));
//#line 366 "/opt/ros/kinetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

      for (std::vector<TerarangerHubMultiflexConfig::AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        __description_message__.groups.push_back(**i);
      }
      __max__.__toMessage__(__description_message__.max, __param_descriptions__, __group_descriptions__);
      __min__.__toMessage__(__description_message__.min, __param_descriptions__, __group_descriptions__);
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__, __group_descriptions__);
    }
    std::vector<TerarangerHubMultiflexConfig::AbstractParamDescriptionConstPtr> __param_descriptions__;
    std::vector<TerarangerHubMultiflexConfig::AbstractGroupDescriptionConstPtr> __group_descriptions__;
    TerarangerHubMultiflexConfig __max__;
    TerarangerHubMultiflexConfig __min__;
    TerarangerHubMultiflexConfig __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;

    static const TerarangerHubMultiflexConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static TerarangerHubMultiflexConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &TerarangerHubMultiflexConfig::__getDescriptionMessage__()
  {
    return __get_statics__()->__description_message__;
  }

  inline const TerarangerHubMultiflexConfig &TerarangerHubMultiflexConfig::__getDefault__()
  {
    return __get_statics__()->__default__;
  }

  inline const TerarangerHubMultiflexConfig &TerarangerHubMultiflexConfig::__getMax__()
  {
    return __get_statics__()->__max__;
  }

  inline const TerarangerHubMultiflexConfig &TerarangerHubMultiflexConfig::__getMin__()
  {
    return __get_statics__()->__min__;
  }

  inline const std::vector<TerarangerHubMultiflexConfig::AbstractParamDescriptionConstPtr> &TerarangerHubMultiflexConfig::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const std::vector<TerarangerHubMultiflexConfig::AbstractGroupDescriptionConstPtr> &TerarangerHubMultiflexConfig::__getGroupDescriptions__()
  {
    return __get_statics__()->__group_descriptions__;
  }

  inline const TerarangerHubMultiflexConfigStatics *TerarangerHubMultiflexConfig::__get_statics__()
  {
    const static TerarangerHubMultiflexConfigStatics *statics;

    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = TerarangerHubMultiflexConfigStatics::get_instance();

    return statics;
  }


}

#undef DYNAMIC_RECONFIGURE_FINAL

#endif // __TERARANGERHUBMULTIFLEXRECONFIGURATOR_H__
