//#line 2 "/opt/ros/kinetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"
// *********************************************************
//
// File autogenerated for the teraranger_evo_cfg package
// by the dynamic_reconfigure package.
// Please do not edit.
//
// ********************************************************/

#ifndef __teraranger_evo_cfg__TERARANGERHUBEVOCONFIG_H__
#define __teraranger_evo_cfg__TERARANGERHUBEVOCONFIG_H__

#if __cplusplus >= 201103L
#define DYNAMIC_RECONFIGURE_FINAL final
#else
#define DYNAMIC_RECONFIGURE_FINAL
#endif

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/Group.h>
#include <dynamic_reconfigure/config_init_mutex.h>
#include <boost/any.hpp>

namespace teraranger_evo_cfg
{
  class TerarangerHubEvoConfigStatics;

  class TerarangerHubEvoConfig
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l,
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }

      virtual void clamp(TerarangerHubEvoConfig &config, const TerarangerHubEvoConfig &max, const TerarangerHubEvoConfig &min) const = 0;
      virtual void calcLevel(uint32_t &level, const TerarangerHubEvoConfig &config1, const TerarangerHubEvoConfig &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, TerarangerHubEvoConfig &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const TerarangerHubEvoConfig &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, TerarangerHubEvoConfig &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const TerarangerHubEvoConfig &config) const = 0;
      virtual void getValue(const TerarangerHubEvoConfig &config, boost::any &val) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template <class T>
    class ParamDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string a_name, std::string a_type, uint32_t a_level,
          std::string a_description, std::string a_edit_method, T TerarangerHubEvoConfig::* a_f) :
        AbstractParamDescription(a_name, a_type, a_level, a_description, a_edit_method),
        field(a_f)
      {}

      T (TerarangerHubEvoConfig::* field);

      virtual void clamp(TerarangerHubEvoConfig &config, const TerarangerHubEvoConfig &max, const TerarangerHubEvoConfig &min) const
      {
        if (config.*field > max.*field)
          config.*field = max.*field;

        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const TerarangerHubEvoConfig &config1, const TerarangerHubEvoConfig &config2) const
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, TerarangerHubEvoConfig &config) const
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const TerarangerHubEvoConfig &config) const
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, TerarangerHubEvoConfig &config) const
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const TerarangerHubEvoConfig &config) const
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }

      virtual void getValue(const TerarangerHubEvoConfig &config, boost::any &val) const
      {
        val = config.*field;
      }
    };

    class AbstractGroupDescription : public dynamic_reconfigure::Group
    {
      public:
      AbstractGroupDescription(std::string n, std::string t, int p, int i, bool s)
      {
        name = n;
        type = t;
        parent = p;
        state = s;
        id = i;
      }

      std::vector<AbstractParamDescriptionConstPtr> abstract_parameters;
      bool state;

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &config) const =0;
      virtual void updateParams(boost::any &cfg, TerarangerHubEvoConfig &top) const= 0;
      virtual void setInitialState(boost::any &cfg) const = 0;


      void convertParams()
      {
        for(std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = abstract_parameters.begin(); i != abstract_parameters.end(); ++i)
        {
          parameters.push_back(dynamic_reconfigure::ParamDescription(**i));
        }
      }
    };

    typedef boost::shared_ptr<AbstractGroupDescription> AbstractGroupDescriptionPtr;
    typedef boost::shared_ptr<const AbstractGroupDescription> AbstractGroupDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template<class T, class PT>
    class GroupDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractGroupDescription
    {
    public:
      GroupDescription(std::string a_name, std::string a_type, int a_parent, int a_id, bool a_s, T PT::* a_f) : AbstractGroupDescription(a_name, a_type, a_parent, a_id, a_s), field(a_f)
      {
      }

      GroupDescription(const GroupDescription<T, PT>& g): AbstractGroupDescription(g.name, g.type, g.parent, g.id, g.state), field(g.field), groups(g.groups)
      {
        parameters = g.parameters;
        abstract_parameters = g.abstract_parameters;
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        if(!dynamic_reconfigure::ConfigTools::getGroupState(msg, name, (*config).*field))
          return false;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          if(!(*i)->fromMessage(msg, n))
            return false;
        }

        return true;
      }

      virtual void setInitialState(boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        T* group = &((*config).*field);
        group->state = state;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = boost::any(&((*config).*field));
          (*i)->setInitialState(n);
        }

      }

      virtual void updateParams(boost::any &cfg, TerarangerHubEvoConfig &top) const
      {
        PT* config = boost::any_cast<PT*>(cfg);

        T* f = &((*config).*field);
        f->setParams(top, abstract_parameters);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          (*i)->updateParams(n, top);
        }
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &cfg) const
      {
        const PT config = boost::any_cast<PT>(cfg);
        dynamic_reconfigure::ConfigTools::appendGroup<T>(msg, name, id, parent, config.*field);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          (*i)->toMessage(msg, config.*field);
        }
      }

      T (PT::* field);
      std::vector<TerarangerHubEvoConfig::AbstractGroupDescriptionConstPtr> groups;
    };

class DEFAULT
{
  public:
    DEFAULT()
    {
      state = true;
      name = "Default";
    }

    void setParams(TerarangerHubEvoConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("Output_Mode"==(*_i)->name){Output_Mode = boost::any_cast<int>(val);}
        if("Rate"==(*_i)->name){Rate = boost::any_cast<int>(val);}
        if("IMU_mode"==(*_i)->name){IMU_mode = boost::any_cast<int>(val);}
        if("Sequence_mode"==(*_i)->name){Sequence_mode = boost::any_cast<int>(val);}
        if("Sensor_type_port_0"==(*_i)->name){Sensor_type_port_0 = boost::any_cast<int>(val);}
        if("Sensor_type_port_1"==(*_i)->name){Sensor_type_port_1 = boost::any_cast<int>(val);}
        if("Sensor_type_port_2"==(*_i)->name){Sensor_type_port_2 = boost::any_cast<int>(val);}
        if("Sensor_type_port_3"==(*_i)->name){Sensor_type_port_3 = boost::any_cast<int>(val);}
        if("Sensor_type_port_4"==(*_i)->name){Sensor_type_port_4 = boost::any_cast<int>(val);}
        if("Sensor_type_port_5"==(*_i)->name){Sensor_type_port_5 = boost::any_cast<int>(val);}
        if("Sensor_type_port_6"==(*_i)->name){Sensor_type_port_6 = boost::any_cast<int>(val);}
        if("Sensor_type_port_7"==(*_i)->name){Sensor_type_port_7 = boost::any_cast<int>(val);}
      }
    }

    int Output_Mode;
int Rate;
int IMU_mode;
int Sequence_mode;
int Sensor_type_port_0;
int Sensor_type_port_1;
int Sensor_type_port_2;
int Sensor_type_port_3;
int Sensor_type_port_4;
int Sensor_type_port_5;
int Sensor_type_port_6;
int Sensor_type_port_7;

    bool state;
    std::string name;

    
}groups;



//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int Output_Mode;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int Rate;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int IMU_mode;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int Sequence_mode;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int Sensor_type_port_0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int Sensor_type_port_1;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int Sensor_type_port_2;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int Sensor_type_port_3;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int Sensor_type_port_4;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int Sensor_type_port_5;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int Sensor_type_port_6;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int Sensor_type_port_7;
//#line 228 "/opt/ros/kinetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();

      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        if ((*i)->fromMessage(msg, *this))
          count++;

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i ++)
      {
        if ((*i)->id == 0)
        {
          boost::any n = boost::any(this);
          (*i)->updateParams(n, *this);
          (*i)->fromMessage(msg, n);
        }
      }

      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("TerarangerHubEvoConfig::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (unsigned int i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (unsigned int i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (unsigned int i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (unsigned int i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__, const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toMessage(msg, *this);

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        if((*i)->id == 0)
        {
          (*i)->toMessage(msg, *this);
        }
      }
    }

    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      __toMessage__(msg, __param_descriptions__, __group_descriptions__);
    }

    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      static bool setup=false;

      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->fromServer(nh, *this);

      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++){
        if (!setup && (*i)->id == 0) {
          setup = true;
          boost::any n = boost::any(this);
          (*i)->setInitialState(n);
        }
      }
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const TerarangerHubEvoConfig &__max__ = __getMax__();
      const TerarangerHubEvoConfig &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const TerarangerHubEvoConfig &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->calcLevel(level, config, *this);
      return level;
    }

    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const TerarangerHubEvoConfig &__getDefault__();
    static const TerarangerHubEvoConfig &__getMax__();
    static const TerarangerHubEvoConfig &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    static const std::vector<AbstractGroupDescriptionConstPtr> &__getGroupDescriptions__();

  private:
    static const TerarangerHubEvoConfigStatics *__get_statics__();
  };

  template <> // Max and min are ignored for strings.
  inline void TerarangerHubEvoConfig::ParamDescription<std::string>::clamp(TerarangerHubEvoConfig &config, const TerarangerHubEvoConfig &max, const TerarangerHubEvoConfig &min) const
  {
    (void) config;
    (void) min;
    (void) max;
    return;
  }

  class TerarangerHubEvoConfigStatics
  {
    friend class TerarangerHubEvoConfig;

    TerarangerHubEvoConfigStatics()
    {
TerarangerHubEvoConfig::GroupDescription<TerarangerHubEvoConfig::DEFAULT, TerarangerHubEvoConfig> Default("Default", "", 0, 0, true, &TerarangerHubEvoConfig::groups);
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.Output_Mode = 0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.Output_Mode = 1;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.Output_Mode = 0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(TerarangerHubEvoConfig::AbstractParamDescriptionConstPtr(new TerarangerHubEvoConfig::ParamDescription<int>("Output_Mode", "int", 0, "Set the output mode", "{'enum_description': 'Set the output mode', 'enum': [{'srcline': 7, 'description': 'Enable binary mode', 'srcfile': '/home/dhruv/final_ws/src/teraranger_array/cfg/TerarangerHubEvo.cfg', 'cconsttype': 'const int', 'value': 0, 'ctype': 'int', 'type': 'int', 'name': 'Binary'}, {'srcline': 8, 'description': 'Enable text mode', 'srcfile': '/home/dhruv/final_ws/src/teraranger_array/cfg/TerarangerHubEvo.cfg', 'cconsttype': 'const int', 'value': 1, 'ctype': 'int', 'type': 'int', 'name': 'Text'}]}", &TerarangerHubEvoConfig::Output_Mode)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(TerarangerHubEvoConfig::AbstractParamDescriptionConstPtr(new TerarangerHubEvoConfig::ParamDescription<int>("Output_Mode", "int", 0, "Set the output mode", "{'enum_description': 'Set the output mode', 'enum': [{'srcline': 7, 'description': 'Enable binary mode', 'srcfile': '/home/dhruv/final_ws/src/teraranger_array/cfg/TerarangerHubEvo.cfg', 'cconsttype': 'const int', 'value': 0, 'ctype': 'int', 'type': 'int', 'name': 'Binary'}, {'srcline': 8, 'description': 'Enable text mode', 'srcfile': '/home/dhruv/final_ws/src/teraranger_array/cfg/TerarangerHubEvo.cfg', 'cconsttype': 'const int', 'value': 1, 'ctype': 'int', 'type': 'int', 'name': 'Text'}]}", &TerarangerHubEvoConfig::Output_Mode)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.Rate = 0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.Rate = 5;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.Rate = 0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(TerarangerHubEvoConfig::AbstractParamDescriptionConstPtr(new TerarangerHubEvoConfig::ParamDescription<int>("Rate", "int", 1, "Set the rate", "{'enum_description': 'Set the rate of update', 'enum': [{'srcline': 11, 'description': 'Send when all measurement available', 'srcfile': '/home/dhruv/final_ws/src/teraranger_array/cfg/TerarangerHubEvo.cfg', 'cconsttype': 'const int', 'value': 0, 'ctype': 'int', 'type': 'int', 'name': 'ASAP'}, {'srcline': 12, 'description': '50 Hz', 'srcfile': '/home/dhruv/final_ws/src/teraranger_array/cfg/TerarangerHubEvo.cfg', 'cconsttype': 'const int', 'value': 1, 'ctype': 'int', 'type': 'int', 'name': '50'}, {'srcline': 13, 'description': '100 Hz', 'srcfile': '/home/dhruv/final_ws/src/teraranger_array/cfg/TerarangerHubEvo.cfg', 'cconsttype': 'const int', 'value': 2, 'ctype': 'int', 'type': 'int', 'name': '100'}, {'srcline': 14, 'description': '250 Hz', 'srcfile': '/home/dhruv/final_ws/src/teraranger_array/cfg/TerarangerHubEvo.cfg', 'cconsttype': 'const int', 'value': 3, 'ctype': 'int', 'type': 'int', 'name': '250'}, {'srcline': 15, 'description': '500 Hz', 'srcfile': '/home/dhruv/final_ws/src/teraranger_array/cfg/TerarangerHubEvo.cfg', 'cconsttype': 'const int', 'value': 4, 'ctype': 'int', 'type': 'int', 'name': '500'}, {'srcline': 16, 'description': '600 Hz', 'srcfile': '/home/dhruv/final_ws/src/teraranger_array/cfg/TerarangerHubEvo.cfg', 'cconsttype': 'const int', 'value': 5, 'ctype': 'int', 'type': 'int', 'name': '600'}]}", &TerarangerHubEvoConfig::Rate)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(TerarangerHubEvoConfig::AbstractParamDescriptionConstPtr(new TerarangerHubEvoConfig::ParamDescription<int>("Rate", "int", 1, "Set the rate", "{'enum_description': 'Set the rate of update', 'enum': [{'srcline': 11, 'description': 'Send when all measurement available', 'srcfile': '/home/dhruv/final_ws/src/teraranger_array/cfg/TerarangerHubEvo.cfg', 'cconsttype': 'const int', 'value': 0, 'ctype': 'int', 'type': 'int', 'name': 'ASAP'}, {'srcline': 12, 'description': '50 Hz', 'srcfile': '/home/dhruv/final_ws/src/teraranger_array/cfg/TerarangerHubEvo.cfg', 'cconsttype': 'const int', 'value': 1, 'ctype': 'int', 'type': 'int', 'name': '50'}, {'srcline': 13, 'description': '100 Hz', 'srcfile': '/home/dhruv/final_ws/src/teraranger_array/cfg/TerarangerHubEvo.cfg', 'cconsttype': 'const int', 'value': 2, 'ctype': 'int', 'type': 'int', 'name': '100'}, {'srcline': 14, 'description': '250 Hz', 'srcfile': '/home/dhruv/final_ws/src/teraranger_array/cfg/TerarangerHubEvo.cfg', 'cconsttype': 'const int', 'value': 3, 'ctype': 'int', 'type': 'int', 'name': '250'}, {'srcline': 15, 'description': '500 Hz', 'srcfile': '/home/dhruv/final_ws/src/teraranger_array/cfg/TerarangerHubEvo.cfg', 'cconsttype': 'const int', 'value': 4, 'ctype': 'int', 'type': 'int', 'name': '500'}, {'srcline': 16, 'description': '600 Hz', 'srcfile': '/home/dhruv/final_ws/src/teraranger_array/cfg/TerarangerHubEvo.cfg', 'cconsttype': 'const int', 'value': 5, 'ctype': 'int', 'type': 'int', 'name': '600'}]}", &TerarangerHubEvoConfig::Rate)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.IMU_mode = 0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.IMU_mode = 3;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.IMU_mode = 0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(TerarangerHubEvoConfig::AbstractParamDescriptionConstPtr(new TerarangerHubEvoConfig::ParamDescription<int>("IMU_mode", "int", 2, "Set imu mode", "{'enum_description': 'Set the IMU mode', 'enum': [{'srcline': 24, 'description': 'IMU disabled', 'srcfile': '/home/dhruv/final_ws/src/teraranger_array/cfg/TerarangerHubEvo.cfg', 'cconsttype': 'const int', 'value': 0, 'ctype': 'int', 'type': 'int', 'name': 'OFF'}, {'srcline': 25, 'description': 'Quaternion mode', 'srcfile': '/home/dhruv/final_ws/src/teraranger_array/cfg/TerarangerHubEvo.cfg', 'cconsttype': 'const int', 'value': 1, 'ctype': 'int', 'type': 'int', 'name': 'QUAT'}, {'srcline': 26, 'description': 'Euler mode', 'srcfile': '/home/dhruv/final_ws/src/teraranger_array/cfg/TerarangerHubEvo.cfg', 'cconsttype': 'const int', 'value': 2, 'ctype': 'int', 'type': 'int', 'name': 'EULER'}, {'srcline': 27, 'description': 'Quaternion and linear mode', 'srcfile': '/home/dhruv/final_ws/src/teraranger_array/cfg/TerarangerHubEvo.cfg', 'cconsttype': 'const int', 'value': 3, 'ctype': 'int', 'type': 'int', 'name': 'QUATLIN'}]}", &TerarangerHubEvoConfig::IMU_mode)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(TerarangerHubEvoConfig::AbstractParamDescriptionConstPtr(new TerarangerHubEvoConfig::ParamDescription<int>("IMU_mode", "int", 2, "Set imu mode", "{'enum_description': 'Set the IMU mode', 'enum': [{'srcline': 24, 'description': 'IMU disabled', 'srcfile': '/home/dhruv/final_ws/src/teraranger_array/cfg/TerarangerHubEvo.cfg', 'cconsttype': 'const int', 'value': 0, 'ctype': 'int', 'type': 'int', 'name': 'OFF'}, {'srcline': 25, 'description': 'Quaternion mode', 'srcfile': '/home/dhruv/final_ws/src/teraranger_array/cfg/TerarangerHubEvo.cfg', 'cconsttype': 'const int', 'value': 1, 'ctype': 'int', 'type': 'int', 'name': 'QUAT'}, {'srcline': 26, 'description': 'Euler mode', 'srcfile': '/home/dhruv/final_ws/src/teraranger_array/cfg/TerarangerHubEvo.cfg', 'cconsttype': 'const int', 'value': 2, 'ctype': 'int', 'type': 'int', 'name': 'EULER'}, {'srcline': 27, 'description': 'Quaternion and linear mode', 'srcfile': '/home/dhruv/final_ws/src/teraranger_array/cfg/TerarangerHubEvo.cfg', 'cconsttype': 'const int', 'value': 3, 'ctype': 'int', 'type': 'int', 'name': 'QUATLIN'}]}", &TerarangerHubEvoConfig::IMU_mode)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.Sequence_mode = 0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.Sequence_mode = 2;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.Sequence_mode = 0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(TerarangerHubEvoConfig::AbstractParamDescriptionConstPtr(new TerarangerHubEvoConfig::ParamDescription<int>("Sequence_mode", "int", 3, "Set the firing sequence", "{'enum_description': 'Set the sensor firing mode', 'enum': [{'srcline': 19, 'description': 'Allows crosstalk', 'srcfile': '/home/dhruv/final_ws/src/teraranger_array/cfg/TerarangerHubEvo.cfg', 'cconsttype': 'const int', 'value': 0, 'ctype': 'int', 'type': 'int', 'name': 'Crosstalk'}, {'srcline': 20, 'description': 'Prevents crosstalk', 'srcfile': '/home/dhruv/final_ws/src/teraranger_array/cfg/TerarangerHubEvo.cfg', 'cconsttype': 'const int', 'value': 1, 'ctype': 'int', 'type': 'int', 'name': 'Anti_crosstalk'}, {'srcline': 21, 'description': 'Prevents crosstalk for tower layout', 'srcfile': '/home/dhruv/final_ws/src/teraranger_array/cfg/TerarangerHubEvo.cfg', 'cconsttype': 'const int', 'value': 2, 'ctype': 'int', 'type': 'int', 'name': 'Tower_mode'}]}", &TerarangerHubEvoConfig::Sequence_mode)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(TerarangerHubEvoConfig::AbstractParamDescriptionConstPtr(new TerarangerHubEvoConfig::ParamDescription<int>("Sequence_mode", "int", 3, "Set the firing sequence", "{'enum_description': 'Set the sensor firing mode', 'enum': [{'srcline': 19, 'description': 'Allows crosstalk', 'srcfile': '/home/dhruv/final_ws/src/teraranger_array/cfg/TerarangerHubEvo.cfg', 'cconsttype': 'const int', 'value': 0, 'ctype': 'int', 'type': 'int', 'name': 'Crosstalk'}, {'srcline': 20, 'description': 'Prevents crosstalk', 'srcfile': '/home/dhruv/final_ws/src/teraranger_array/cfg/TerarangerHubEvo.cfg', 'cconsttype': 'const int', 'value': 1, 'ctype': 'int', 'type': 'int', 'name': 'Anti_crosstalk'}, {'srcline': 21, 'description': 'Prevents crosstalk for tower layout', 'srcfile': '/home/dhruv/final_ws/src/teraranger_array/cfg/TerarangerHubEvo.cfg', 'cconsttype': 'const int', 'value': 2, 'ctype': 'int', 'type': 'int', 'name': 'Tower_mode'}]}", &TerarangerHubEvoConfig::Sequence_mode)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.Sensor_type_port_0 = 0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.Sensor_type_port_0 = 3;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.Sensor_type_port_0 = 1;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(TerarangerHubEvoConfig::AbstractParamDescriptionConstPtr(new TerarangerHubEvoConfig::ParamDescription<int>("Sensor_type_port_0", "int", 4, "Set the sensor type", "{'enum_description': 'Set the type of the sensor', 'enum': [{'srcline': 30, 'description': 'Evo 600 Hz', 'srcfile': '/home/dhruv/final_ws/src/teraranger_array/cfg/TerarangerHubEvo.cfg', 'cconsttype': 'const int', 'value': 0, 'ctype': 'int', 'type': 'int', 'name': 'EVO_600HZ'}, {'srcline': 31, 'description': 'Evo 60 m', 'srcfile': '/home/dhruv/final_ws/src/teraranger_array/cfg/TerarangerHubEvo.cfg', 'cconsttype': 'const int', 'value': 1, 'ctype': 'int', 'type': 'int', 'name': 'EVO_60M'}, {'srcline': 32, 'description': 'Evo 3 m', 'srcfile': '/home/dhruv/final_ws/src/teraranger_array/cfg/TerarangerHubEvo.cfg', 'cconsttype': 'const int', 'value': 2, 'ctype': 'int', 'type': 'int', 'name': 'EVO_3M'}, {'srcline': 33, 'description': 'Evo Mini', 'srcfile': '/home/dhruv/final_ws/src/teraranger_array/cfg/TerarangerHubEvo.cfg', 'cconsttype': 'const int', 'value': 3, 'ctype': 'int', 'type': 'int', 'name': 'EVO_MINI'}]}", &TerarangerHubEvoConfig::Sensor_type_port_0)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(TerarangerHubEvoConfig::AbstractParamDescriptionConstPtr(new TerarangerHubEvoConfig::ParamDescription<int>("Sensor_type_port_0", "int", 4, "Set the sensor type", "{'enum_description': 'Set the type of the sensor', 'enum': [{'srcline': 30, 'description': 'Evo 600 Hz', 'srcfile': '/home/dhruv/final_ws/src/teraranger_array/cfg/TerarangerHubEvo.cfg', 'cconsttype': 'const int', 'value': 0, 'ctype': 'int', 'type': 'int', 'name': 'EVO_600HZ'}, {'srcline': 31, 'description': 'Evo 60 m', 'srcfile': '/home/dhruv/final_ws/src/teraranger_array/cfg/TerarangerHubEvo.cfg', 'cconsttype': 'const int', 'value': 1, 'ctype': 'int', 'type': 'int', 'name': 'EVO_60M'}, {'srcline': 32, 'description': 'Evo 3 m', 'srcfile': '/home/dhruv/final_ws/src/teraranger_array/cfg/TerarangerHubEvo.cfg', 'cconsttype': 'const int', 'value': 2, 'ctype': 'int', 'type': 'int', 'name': 'EVO_3M'}, {'srcline': 33, 'description': 'Evo Mini', 'srcfile': '/home/dhruv/final_ws/src/teraranger_array/cfg/TerarangerHubEvo.cfg', 'cconsttype': 'const int', 'value': 3, 'ctype': 'int', 'type': 'int', 'name': 'EVO_MINI'}]}", &TerarangerHubEvoConfig::Sensor_type_port_0)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.Sensor_type_port_1 = 0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.Sensor_type_port_1 = 3;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.Sensor_type_port_1 = 1;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(TerarangerHubEvoConfig::AbstractParamDescriptionConstPtr(new TerarangerHubEvoConfig::ParamDescription<int>("Sensor_type_port_1", "int", 4, "Set the sensor type", "{'enum_description': 'Set the type of the sensor', 'enum': [{'srcline': 30, 'description': 'Evo 600 Hz', 'srcfile': '/home/dhruv/final_ws/src/teraranger_array/cfg/TerarangerHubEvo.cfg', 'cconsttype': 'const int', 'value': 0, 'ctype': 'int', 'type': 'int', 'name': 'EVO_600HZ'}, {'srcline': 31, 'description': 'Evo 60 m', 'srcfile': '/home/dhruv/final_ws/src/teraranger_array/cfg/TerarangerHubEvo.cfg', 'cconsttype': 'const int', 'value': 1, 'ctype': 'int', 'type': 'int', 'name': 'EVO_60M'}, {'srcline': 32, 'description': 'Evo 3 m', 'srcfile': '/home/dhruv/final_ws/src/teraranger_array/cfg/TerarangerHubEvo.cfg', 'cconsttype': 'const int', 'value': 2, 'ctype': 'int', 'type': 'int', 'name': 'EVO_3M'}, {'srcline': 33, 'description': 'Evo Mini', 'srcfile': '/home/dhruv/final_ws/src/teraranger_array/cfg/TerarangerHubEvo.cfg', 'cconsttype': 'const int', 'value': 3, 'ctype': 'int', 'type': 'int', 'name': 'EVO_MINI'}]}", &TerarangerHubEvoConfig::Sensor_type_port_1)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(TerarangerHubEvoConfig::AbstractParamDescriptionConstPtr(new TerarangerHubEvoConfig::ParamDescription<int>("Sensor_type_port_1", "int", 4, "Set the sensor type", "{'enum_description': 'Set the type of the sensor', 'enum': [{'srcline': 30, 'description': 'Evo 600 Hz', 'srcfile': '/home/dhruv/final_ws/src/teraranger_array/cfg/TerarangerHubEvo.cfg', 'cconsttype': 'const int', 'value': 0, 'ctype': 'int', 'type': 'int', 'name': 'EVO_600HZ'}, {'srcline': 31, 'description': 'Evo 60 m', 'srcfile': '/home/dhruv/final_ws/src/teraranger_array/cfg/TerarangerHubEvo.cfg', 'cconsttype': 'const int', 'value': 1, 'ctype': 'int', 'type': 'int', 'name': 'EVO_60M'}, {'srcline': 32, 'description': 'Evo 3 m', 'srcfile': '/home/dhruv/final_ws/src/teraranger_array/cfg/TerarangerHubEvo.cfg', 'cconsttype': 'const int', 'value': 2, 'ctype': 'int', 'type': 'int', 'name': 'EVO_3M'}, {'srcline': 33, 'description': 'Evo Mini', 'srcfile': '/home/dhruv/final_ws/src/teraranger_array/cfg/TerarangerHubEvo.cfg', 'cconsttype': 'const int', 'value': 3, 'ctype': 'int', 'type': 'int', 'name': 'EVO_MINI'}]}", &TerarangerHubEvoConfig::Sensor_type_port_1)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.Sensor_type_port_2 = 0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.Sensor_type_port_2 = 3;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.Sensor_type_port_2 = 1;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(TerarangerHubEvoConfig::AbstractParamDescriptionConstPtr(new TerarangerHubEvoConfig::ParamDescription<int>("Sensor_type_port_2", "int", 4, "Set the sensor type", "{'enum_description': 'Set the type of the sensor', 'enum': [{'srcline': 30, 'description': 'Evo 600 Hz', 'srcfile': '/home/dhruv/final_ws/src/teraranger_array/cfg/TerarangerHubEvo.cfg', 'cconsttype': 'const int', 'value': 0, 'ctype': 'int', 'type': 'int', 'name': 'EVO_600HZ'}, {'srcline': 31, 'description': 'Evo 60 m', 'srcfile': '/home/dhruv/final_ws/src/teraranger_array/cfg/TerarangerHubEvo.cfg', 'cconsttype': 'const int', 'value': 1, 'ctype': 'int', 'type': 'int', 'name': 'EVO_60M'}, {'srcline': 32, 'description': 'Evo 3 m', 'srcfile': '/home/dhruv/final_ws/src/teraranger_array/cfg/TerarangerHubEvo.cfg', 'cconsttype': 'const int', 'value': 2, 'ctype': 'int', 'type': 'int', 'name': 'EVO_3M'}, {'srcline': 33, 'description': 'Evo Mini', 'srcfile': '/home/dhruv/final_ws/src/teraranger_array/cfg/TerarangerHubEvo.cfg', 'cconsttype': 'const int', 'value': 3, 'ctype': 'int', 'type': 'int', 'name': 'EVO_MINI'}]}", &TerarangerHubEvoConfig::Sensor_type_port_2)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(TerarangerHubEvoConfig::AbstractParamDescriptionConstPtr(new TerarangerHubEvoConfig::ParamDescription<int>("Sensor_type_port_2", "int", 4, "Set the sensor type", "{'enum_description': 'Set the type of the sensor', 'enum': [{'srcline': 30, 'description': 'Evo 600 Hz', 'srcfile': '/home/dhruv/final_ws/src/teraranger_array/cfg/TerarangerHubEvo.cfg', 'cconsttype': 'const int', 'value': 0, 'ctype': 'int', 'type': 'int', 'name': 'EVO_600HZ'}, {'srcline': 31, 'description': 'Evo 60 m', 'srcfile': '/home/dhruv/final_ws/src/teraranger_array/cfg/TerarangerHubEvo.cfg', 'cconsttype': 'const int', 'value': 1, 'ctype': 'int', 'type': 'int', 'name': 'EVO_60M'}, {'srcline': 32, 'description': 'Evo 3 m', 'srcfile': '/home/dhruv/final_ws/src/teraranger_array/cfg/TerarangerHubEvo.cfg', 'cconsttype': 'const int', 'value': 2, 'ctype': 'int', 'type': 'int', 'name': 'EVO_3M'}, {'srcline': 33, 'description': 'Evo Mini', 'srcfile': '/home/dhruv/final_ws/src/teraranger_array/cfg/TerarangerHubEvo.cfg', 'cconsttype': 'const int', 'value': 3, 'ctype': 'int', 'type': 'int', 'name': 'EVO_MINI'}]}", &TerarangerHubEvoConfig::Sensor_type_port_2)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.Sensor_type_port_3 = 0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.Sensor_type_port_3 = 3;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.Sensor_type_port_3 = 1;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(TerarangerHubEvoConfig::AbstractParamDescriptionConstPtr(new TerarangerHubEvoConfig::ParamDescription<int>("Sensor_type_port_3", "int", 4, "Set the sensor type", "{'enum_description': 'Set the type of the sensor', 'enum': [{'srcline': 30, 'description': 'Evo 600 Hz', 'srcfile': '/home/dhruv/final_ws/src/teraranger_array/cfg/TerarangerHubEvo.cfg', 'cconsttype': 'const int', 'value': 0, 'ctype': 'int', 'type': 'int', 'name': 'EVO_600HZ'}, {'srcline': 31, 'description': 'Evo 60 m', 'srcfile': '/home/dhruv/final_ws/src/teraranger_array/cfg/TerarangerHubEvo.cfg', 'cconsttype': 'const int', 'value': 1, 'ctype': 'int', 'type': 'int', 'name': 'EVO_60M'}, {'srcline': 32, 'description': 'Evo 3 m', 'srcfile': '/home/dhruv/final_ws/src/teraranger_array/cfg/TerarangerHubEvo.cfg', 'cconsttype': 'const int', 'value': 2, 'ctype': 'int', 'type': 'int', 'name': 'EVO_3M'}, {'srcline': 33, 'description': 'Evo Mini', 'srcfile': '/home/dhruv/final_ws/src/teraranger_array/cfg/TerarangerHubEvo.cfg', 'cconsttype': 'const int', 'value': 3, 'ctype': 'int', 'type': 'int', 'name': 'EVO_MINI'}]}", &TerarangerHubEvoConfig::Sensor_type_port_3)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(TerarangerHubEvoConfig::AbstractParamDescriptionConstPtr(new TerarangerHubEvoConfig::ParamDescription<int>("Sensor_type_port_3", "int", 4, "Set the sensor type", "{'enum_description': 'Set the type of the sensor', 'enum': [{'srcline': 30, 'description': 'Evo 600 Hz', 'srcfile': '/home/dhruv/final_ws/src/teraranger_array/cfg/TerarangerHubEvo.cfg', 'cconsttype': 'const int', 'value': 0, 'ctype': 'int', 'type': 'int', 'name': 'EVO_600HZ'}, {'srcline': 31, 'description': 'Evo 60 m', 'srcfile': '/home/dhruv/final_ws/src/teraranger_array/cfg/TerarangerHubEvo.cfg', 'cconsttype': 'const int', 'value': 1, 'ctype': 'int', 'type': 'int', 'name': 'EVO_60M'}, {'srcline': 32, 'description': 'Evo 3 m', 'srcfile': '/home/dhruv/final_ws/src/teraranger_array/cfg/TerarangerHubEvo.cfg', 'cconsttype': 'const int', 'value': 2, 'ctype': 'int', 'type': 'int', 'name': 'EVO_3M'}, {'srcline': 33, 'description': 'Evo Mini', 'srcfile': '/home/dhruv/final_ws/src/teraranger_array/cfg/TerarangerHubEvo.cfg', 'cconsttype': 'const int', 'value': 3, 'ctype': 'int', 'type': 'int', 'name': 'EVO_MINI'}]}", &TerarangerHubEvoConfig::Sensor_type_port_3)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.Sensor_type_port_4 = 0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.Sensor_type_port_4 = 3;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.Sensor_type_port_4 = 1;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(TerarangerHubEvoConfig::AbstractParamDescriptionConstPtr(new TerarangerHubEvoConfig::ParamDescription<int>("Sensor_type_port_4", "int", 4, "Set the sensor type", "{'enum_description': 'Set the type of the sensor', 'enum': [{'srcline': 30, 'description': 'Evo 600 Hz', 'srcfile': '/home/dhruv/final_ws/src/teraranger_array/cfg/TerarangerHubEvo.cfg', 'cconsttype': 'const int', 'value': 0, 'ctype': 'int', 'type': 'int', 'name': 'EVO_600HZ'}, {'srcline': 31, 'description': 'Evo 60 m', 'srcfile': '/home/dhruv/final_ws/src/teraranger_array/cfg/TerarangerHubEvo.cfg', 'cconsttype': 'const int', 'value': 1, 'ctype': 'int', 'type': 'int', 'name': 'EVO_60M'}, {'srcline': 32, 'description': 'Evo 3 m', 'srcfile': '/home/dhruv/final_ws/src/teraranger_array/cfg/TerarangerHubEvo.cfg', 'cconsttype': 'const int', 'value': 2, 'ctype': 'int', 'type': 'int', 'name': 'EVO_3M'}, {'srcline': 33, 'description': 'Evo Mini', 'srcfile': '/home/dhruv/final_ws/src/teraranger_array/cfg/TerarangerHubEvo.cfg', 'cconsttype': 'const int', 'value': 3, 'ctype': 'int', 'type': 'int', 'name': 'EVO_MINI'}]}", &TerarangerHubEvoConfig::Sensor_type_port_4)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(TerarangerHubEvoConfig::AbstractParamDescriptionConstPtr(new TerarangerHubEvoConfig::ParamDescription<int>("Sensor_type_port_4", "int", 4, "Set the sensor type", "{'enum_description': 'Set the type of the sensor', 'enum': [{'srcline': 30, 'description': 'Evo 600 Hz', 'srcfile': '/home/dhruv/final_ws/src/teraranger_array/cfg/TerarangerHubEvo.cfg', 'cconsttype': 'const int', 'value': 0, 'ctype': 'int', 'type': 'int', 'name': 'EVO_600HZ'}, {'srcline': 31, 'description': 'Evo 60 m', 'srcfile': '/home/dhruv/final_ws/src/teraranger_array/cfg/TerarangerHubEvo.cfg', 'cconsttype': 'const int', 'value': 1, 'ctype': 'int', 'type': 'int', 'name': 'EVO_60M'}, {'srcline': 32, 'description': 'Evo 3 m', 'srcfile': '/home/dhruv/final_ws/src/teraranger_array/cfg/TerarangerHubEvo.cfg', 'cconsttype': 'const int', 'value': 2, 'ctype': 'int', 'type': 'int', 'name': 'EVO_3M'}, {'srcline': 33, 'description': 'Evo Mini', 'srcfile': '/home/dhruv/final_ws/src/teraranger_array/cfg/TerarangerHubEvo.cfg', 'cconsttype': 'const int', 'value': 3, 'ctype': 'int', 'type': 'int', 'name': 'EVO_MINI'}]}", &TerarangerHubEvoConfig::Sensor_type_port_4)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.Sensor_type_port_5 = 0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.Sensor_type_port_5 = 3;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.Sensor_type_port_5 = 1;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(TerarangerHubEvoConfig::AbstractParamDescriptionConstPtr(new TerarangerHubEvoConfig::ParamDescription<int>("Sensor_type_port_5", "int", 4, "Set the sensor type", "{'enum_description': 'Set the type of the sensor', 'enum': [{'srcline': 30, 'description': 'Evo 600 Hz', 'srcfile': '/home/dhruv/final_ws/src/teraranger_array/cfg/TerarangerHubEvo.cfg', 'cconsttype': 'const int', 'value': 0, 'ctype': 'int', 'type': 'int', 'name': 'EVO_600HZ'}, {'srcline': 31, 'description': 'Evo 60 m', 'srcfile': '/home/dhruv/final_ws/src/teraranger_array/cfg/TerarangerHubEvo.cfg', 'cconsttype': 'const int', 'value': 1, 'ctype': 'int', 'type': 'int', 'name': 'EVO_60M'}, {'srcline': 32, 'description': 'Evo 3 m', 'srcfile': '/home/dhruv/final_ws/src/teraranger_array/cfg/TerarangerHubEvo.cfg', 'cconsttype': 'const int', 'value': 2, 'ctype': 'int', 'type': 'int', 'name': 'EVO_3M'}, {'srcline': 33, 'description': 'Evo Mini', 'srcfile': '/home/dhruv/final_ws/src/teraranger_array/cfg/TerarangerHubEvo.cfg', 'cconsttype': 'const int', 'value': 3, 'ctype': 'int', 'type': 'int', 'name': 'EVO_MINI'}]}", &TerarangerHubEvoConfig::Sensor_type_port_5)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(TerarangerHubEvoConfig::AbstractParamDescriptionConstPtr(new TerarangerHubEvoConfig::ParamDescription<int>("Sensor_type_port_5", "int", 4, "Set the sensor type", "{'enum_description': 'Set the type of the sensor', 'enum': [{'srcline': 30, 'description': 'Evo 600 Hz', 'srcfile': '/home/dhruv/final_ws/src/teraranger_array/cfg/TerarangerHubEvo.cfg', 'cconsttype': 'const int', 'value': 0, 'ctype': 'int', 'type': 'int', 'name': 'EVO_600HZ'}, {'srcline': 31, 'description': 'Evo 60 m', 'srcfile': '/home/dhruv/final_ws/src/teraranger_array/cfg/TerarangerHubEvo.cfg', 'cconsttype': 'const int', 'value': 1, 'ctype': 'int', 'type': 'int', 'name': 'EVO_60M'}, {'srcline': 32, 'description': 'Evo 3 m', 'srcfile': '/home/dhruv/final_ws/src/teraranger_array/cfg/TerarangerHubEvo.cfg', 'cconsttype': 'const int', 'value': 2, 'ctype': 'int', 'type': 'int', 'name': 'EVO_3M'}, {'srcline': 33, 'description': 'Evo Mini', 'srcfile': '/home/dhruv/final_ws/src/teraranger_array/cfg/TerarangerHubEvo.cfg', 'cconsttype': 'const int', 'value': 3, 'ctype': 'int', 'type': 'int', 'name': 'EVO_MINI'}]}", &TerarangerHubEvoConfig::Sensor_type_port_5)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.Sensor_type_port_6 = 0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.Sensor_type_port_6 = 3;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.Sensor_type_port_6 = 1;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(TerarangerHubEvoConfig::AbstractParamDescriptionConstPtr(new TerarangerHubEvoConfig::ParamDescription<int>("Sensor_type_port_6", "int", 4, "Set the sensor type", "{'enum_description': 'Set the type of the sensor', 'enum': [{'srcline': 30, 'description': 'Evo 600 Hz', 'srcfile': '/home/dhruv/final_ws/src/teraranger_array/cfg/TerarangerHubEvo.cfg', 'cconsttype': 'const int', 'value': 0, 'ctype': 'int', 'type': 'int', 'name': 'EVO_600HZ'}, {'srcline': 31, 'description': 'Evo 60 m', 'srcfile': '/home/dhruv/final_ws/src/teraranger_array/cfg/TerarangerHubEvo.cfg', 'cconsttype': 'const int', 'value': 1, 'ctype': 'int', 'type': 'int', 'name': 'EVO_60M'}, {'srcline': 32, 'description': 'Evo 3 m', 'srcfile': '/home/dhruv/final_ws/src/teraranger_array/cfg/TerarangerHubEvo.cfg', 'cconsttype': 'const int', 'value': 2, 'ctype': 'int', 'type': 'int', 'name': 'EVO_3M'}, {'srcline': 33, 'description': 'Evo Mini', 'srcfile': '/home/dhruv/final_ws/src/teraranger_array/cfg/TerarangerHubEvo.cfg', 'cconsttype': 'const int', 'value': 3, 'ctype': 'int', 'type': 'int', 'name': 'EVO_MINI'}]}", &TerarangerHubEvoConfig::Sensor_type_port_6)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(TerarangerHubEvoConfig::AbstractParamDescriptionConstPtr(new TerarangerHubEvoConfig::ParamDescription<int>("Sensor_type_port_6", "int", 4, "Set the sensor type", "{'enum_description': 'Set the type of the sensor', 'enum': [{'srcline': 30, 'description': 'Evo 600 Hz', 'srcfile': '/home/dhruv/final_ws/src/teraranger_array/cfg/TerarangerHubEvo.cfg', 'cconsttype': 'const int', 'value': 0, 'ctype': 'int', 'type': 'int', 'name': 'EVO_600HZ'}, {'srcline': 31, 'description': 'Evo 60 m', 'srcfile': '/home/dhruv/final_ws/src/teraranger_array/cfg/TerarangerHubEvo.cfg', 'cconsttype': 'const int', 'value': 1, 'ctype': 'int', 'type': 'int', 'name': 'EVO_60M'}, {'srcline': 32, 'description': 'Evo 3 m', 'srcfile': '/home/dhruv/final_ws/src/teraranger_array/cfg/TerarangerHubEvo.cfg', 'cconsttype': 'const int', 'value': 2, 'ctype': 'int', 'type': 'int', 'name': 'EVO_3M'}, {'srcline': 33, 'description': 'Evo Mini', 'srcfile': '/home/dhruv/final_ws/src/teraranger_array/cfg/TerarangerHubEvo.cfg', 'cconsttype': 'const int', 'value': 3, 'ctype': 'int', 'type': 'int', 'name': 'EVO_MINI'}]}", &TerarangerHubEvoConfig::Sensor_type_port_6)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.Sensor_type_port_7 = 0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.Sensor_type_port_7 = 3;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.Sensor_type_port_7 = 1;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(TerarangerHubEvoConfig::AbstractParamDescriptionConstPtr(new TerarangerHubEvoConfig::ParamDescription<int>("Sensor_type_port_7", "int", 4, "Set the sensor type", "{'enum_description': 'Set the type of the sensor', 'enum': [{'srcline': 30, 'description': 'Evo 600 Hz', 'srcfile': '/home/dhruv/final_ws/src/teraranger_array/cfg/TerarangerHubEvo.cfg', 'cconsttype': 'const int', 'value': 0, 'ctype': 'int', 'type': 'int', 'name': 'EVO_600HZ'}, {'srcline': 31, 'description': 'Evo 60 m', 'srcfile': '/home/dhruv/final_ws/src/teraranger_array/cfg/TerarangerHubEvo.cfg', 'cconsttype': 'const int', 'value': 1, 'ctype': 'int', 'type': 'int', 'name': 'EVO_60M'}, {'srcline': 32, 'description': 'Evo 3 m', 'srcfile': '/home/dhruv/final_ws/src/teraranger_array/cfg/TerarangerHubEvo.cfg', 'cconsttype': 'const int', 'value': 2, 'ctype': 'int', 'type': 'int', 'name': 'EVO_3M'}, {'srcline': 33, 'description': 'Evo Mini', 'srcfile': '/home/dhruv/final_ws/src/teraranger_array/cfg/TerarangerHubEvo.cfg', 'cconsttype': 'const int', 'value': 3, 'ctype': 'int', 'type': 'int', 'name': 'EVO_MINI'}]}", &TerarangerHubEvoConfig::Sensor_type_port_7)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(TerarangerHubEvoConfig::AbstractParamDescriptionConstPtr(new TerarangerHubEvoConfig::ParamDescription<int>("Sensor_type_port_7", "int", 4, "Set the sensor type", "{'enum_description': 'Set the type of the sensor', 'enum': [{'srcline': 30, 'description': 'Evo 600 Hz', 'srcfile': '/home/dhruv/final_ws/src/teraranger_array/cfg/TerarangerHubEvo.cfg', 'cconsttype': 'const int', 'value': 0, 'ctype': 'int', 'type': 'int', 'name': 'EVO_600HZ'}, {'srcline': 31, 'description': 'Evo 60 m', 'srcfile': '/home/dhruv/final_ws/src/teraranger_array/cfg/TerarangerHubEvo.cfg', 'cconsttype': 'const int', 'value': 1, 'ctype': 'int', 'type': 'int', 'name': 'EVO_60M'}, {'srcline': 32, 'description': 'Evo 3 m', 'srcfile': '/home/dhruv/final_ws/src/teraranger_array/cfg/TerarangerHubEvo.cfg', 'cconsttype': 'const int', 'value': 2, 'ctype': 'int', 'type': 'int', 'name': 'EVO_3M'}, {'srcline': 33, 'description': 'Evo Mini', 'srcfile': '/home/dhruv/final_ws/src/teraranger_array/cfg/TerarangerHubEvo.cfg', 'cconsttype': 'const int', 'value': 3, 'ctype': 'int', 'type': 'int', 'name': 'EVO_MINI'}]}", &TerarangerHubEvoConfig::Sensor_type_port_7)));
//#line 245 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.convertParams();
//#line 245 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(TerarangerHubEvoConfig::AbstractGroupDescriptionConstPtr(new TerarangerHubEvoConfig::GroupDescription<TerarangerHubEvoConfig::DEFAULT, TerarangerHubEvoConfig>(Default)));
//#line 366 "/opt/ros/kinetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

      for (std::vector<TerarangerHubEvoConfig::AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        __description_message__.groups.push_back(**i);
      }
      __max__.__toMessage__(__description_message__.max, __param_descriptions__, __group_descriptions__);
      __min__.__toMessage__(__description_message__.min, __param_descriptions__, __group_descriptions__);
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__, __group_descriptions__);
    }
    std::vector<TerarangerHubEvoConfig::AbstractParamDescriptionConstPtr> __param_descriptions__;
    std::vector<TerarangerHubEvoConfig::AbstractGroupDescriptionConstPtr> __group_descriptions__;
    TerarangerHubEvoConfig __max__;
    TerarangerHubEvoConfig __min__;
    TerarangerHubEvoConfig __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;

    static const TerarangerHubEvoConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static TerarangerHubEvoConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &TerarangerHubEvoConfig::__getDescriptionMessage__()
  {
    return __get_statics__()->__description_message__;
  }

  inline const TerarangerHubEvoConfig &TerarangerHubEvoConfig::__getDefault__()
  {
    return __get_statics__()->__default__;
  }

  inline const TerarangerHubEvoConfig &TerarangerHubEvoConfig::__getMax__()
  {
    return __get_statics__()->__max__;
  }

  inline const TerarangerHubEvoConfig &TerarangerHubEvoConfig::__getMin__()
  {
    return __get_statics__()->__min__;
  }

  inline const std::vector<TerarangerHubEvoConfig::AbstractParamDescriptionConstPtr> &TerarangerHubEvoConfig::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const std::vector<TerarangerHubEvoConfig::AbstractGroupDescriptionConstPtr> &TerarangerHubEvoConfig::__getGroupDescriptions__()
  {
    return __get_statics__()->__group_descriptions__;
  }

  inline const TerarangerHubEvoConfigStatics *TerarangerHubEvoConfig::__get_statics__()
  {
    const static TerarangerHubEvoConfigStatics *statics;

    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = TerarangerHubEvoConfigStatics::get_instance();

    return statics;
  }

//#line 7 "/home/dhruv/final_ws/src/teraranger_array/cfg/TerarangerHubEvo.cfg"
      const int TerarangerHubEvo_Binary = 0;
//#line 8 "/home/dhruv/final_ws/src/teraranger_array/cfg/TerarangerHubEvo.cfg"
      const int TerarangerHubEvo_Text = 1;
//#line 11 "/home/dhruv/final_ws/src/teraranger_array/cfg/TerarangerHubEvo.cfg"
      const int TerarangerHubEvo_ASAP = 0;
//#line 12 "/home/dhruv/final_ws/src/teraranger_array/cfg/TerarangerHubEvo.cfg"
      const int TerarangerHubEvo_50 = 1;
//#line 13 "/home/dhruv/final_ws/src/teraranger_array/cfg/TerarangerHubEvo.cfg"
      const int TerarangerHubEvo_100 = 2;
//#line 14 "/home/dhruv/final_ws/src/teraranger_array/cfg/TerarangerHubEvo.cfg"
      const int TerarangerHubEvo_250 = 3;
//#line 15 "/home/dhruv/final_ws/src/teraranger_array/cfg/TerarangerHubEvo.cfg"
      const int TerarangerHubEvo_500 = 4;
//#line 16 "/home/dhruv/final_ws/src/teraranger_array/cfg/TerarangerHubEvo.cfg"
      const int TerarangerHubEvo_600 = 5;
//#line 19 "/home/dhruv/final_ws/src/teraranger_array/cfg/TerarangerHubEvo.cfg"
      const int TerarangerHubEvo_Crosstalk = 0;
//#line 20 "/home/dhruv/final_ws/src/teraranger_array/cfg/TerarangerHubEvo.cfg"
      const int TerarangerHubEvo_Anti_crosstalk = 1;
//#line 21 "/home/dhruv/final_ws/src/teraranger_array/cfg/TerarangerHubEvo.cfg"
      const int TerarangerHubEvo_Tower_mode = 2;
//#line 24 "/home/dhruv/final_ws/src/teraranger_array/cfg/TerarangerHubEvo.cfg"
      const int TerarangerHubEvo_OFF = 0;
//#line 25 "/home/dhruv/final_ws/src/teraranger_array/cfg/TerarangerHubEvo.cfg"
      const int TerarangerHubEvo_QUAT = 1;
//#line 26 "/home/dhruv/final_ws/src/teraranger_array/cfg/TerarangerHubEvo.cfg"
      const int TerarangerHubEvo_EULER = 2;
//#line 27 "/home/dhruv/final_ws/src/teraranger_array/cfg/TerarangerHubEvo.cfg"
      const int TerarangerHubEvo_QUATLIN = 3;
//#line 30 "/home/dhruv/final_ws/src/teraranger_array/cfg/TerarangerHubEvo.cfg"
      const int TerarangerHubEvo_EVO_600HZ = 0;
//#line 31 "/home/dhruv/final_ws/src/teraranger_array/cfg/TerarangerHubEvo.cfg"
      const int TerarangerHubEvo_EVO_60M = 1;
//#line 32 "/home/dhruv/final_ws/src/teraranger_array/cfg/TerarangerHubEvo.cfg"
      const int TerarangerHubEvo_EVO_3M = 2;
//#line 33 "/home/dhruv/final_ws/src/teraranger_array/cfg/TerarangerHubEvo.cfg"
      const int TerarangerHubEvo_EVO_MINI = 3;
}

#undef DYNAMIC_RECONFIGURE_FINAL

#endif // __TERARANGERHUBEVORECONFIGURATOR_H__
