package rocon_std_msgs;

import org.ros.internal.message.Message;
import uuid_msgs.UniqueID;

public interface StringsPairRequest extends Message {
    public static final String _DEFINITION = "# ====== DO NOT MODIFY! AUTOGENERATED FROM A SERVICE PAIR DEFINITION ======\n\nuuid_msgs/UniqueID id\nStringsRequest request\n";
    public static final String _TYPE = "rocon_std_msgs/StringsPairRequest";

    UniqueID getId();

    StringsRequest getRequest();

    void setId(UniqueID uniqueID);

    void setRequest(StringsRequest stringsRequest);
}
