package rocon_std_msgs;

import org.ros.internal.message.Message;

public interface StringsRequest extends Message {
    public static final String _DEFINITION = "# ====== DO NOT MODIFY! AUTOGENERATED FROM A SERVICE PAIR DEFINITION ======\n\nstring data\n";
    public static final String _TYPE = "rocon_std_msgs/StringsRequest";

    String getData();

    void setData(String str);
}
