package nav_msgs;

import actionlib_msgs.GoalID;
import org.ros.internal.message.Message;
import std_msgs.Header;

public interface GetMapActionGoal extends Message {
    public static final String _DEFINITION = "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\nHeader header\nactionlib_msgs/GoalID goal_id\nnav_msgs/GetMapGoal goal";
    public static final String _TYPE = "nav_msgs/GetMapActionGoal";

    GetMapGoal getGoal();

    GoalID getGoalId();

    Header getHeader();

    void setGoal(GetMapGoal getMapGoal);

    void setGoalId(GoalID goalID);

    void setHeader(Header header);
}
