package nav_msgs;

import org.ros.internal.message.Message;

public interface GetMapResult extends Message {
    public static final String _DEFINITION = "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n#result definitionnav_msgs/OccupancyGrid map";
    public static final String _TYPE = "nav_msgs/GetMapResult";
}
