package nav_msgs;

import org.ros.internal.message.Message;

public interface GetMapFeedback extends Message {
    public static final String _DEFINITION = "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n#feedback definition\n";
    public static final String _TYPE = "nav_msgs/GetMapFeedback";
}
