package nav_msgs;

import actionlib_msgs.GoalStatus;
import org.ros.internal.message.Message;
import std_msgs.Header;

public interface GetMapActionFeedback extends Message {
    public static final String _DEFINITION = "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\nHeader header\nactionlib_msgs/GoalStatus status\nnav_msgs/GetMapFeedback feedback";
    public static final String _TYPE = "nav_msgs/GetMapActionFeedback";

    GetMapFeedback getFeedback();

    Header getHeader();

    GoalStatus getStatus();

    void setFeedback(GetMapFeedback getMapFeedback);

    void setHeader(Header header);

    void setStatus(GoalStatus goalStatus);
}
