package org.ros.internal.message.action;

import org.ros.internal.message.MessageGenerationTemplate;

public class ActionGenerationTemplateFeedback implements MessageGenerationTemplate {
    public String applyTemplate(String messageSource) {
        return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n#feedback definition\n" + messageSource;
    }
}
