package org.apache.commons.httpclient;

public class Header extends NameValuePair {
    private boolean isAutogenerated;

    public Header() {
        this((String) null, (String) null);
    }

    public Header(String name, String value) {
        super(name, value);
        this.isAutogenerated = false;
    }

    public Header(String name, String value, boolean isAutogenerated2) {
        super(name, value);
        this.isAutogenerated = false;
        this.isAutogenerated = isAutogenerated2;
    }

    public String toExternalForm() {
        StringBuffer stringBuffer = new StringBuffer();
        stringBuffer.append(getName() == null ? "" : getName());
        stringBuffer.append(": ");
        stringBuffer.append(getValue() == null ? "" : getValue());
        stringBuffer.append("\r\n");
        return stringBuffer.toString();
    }

    public String toString() {
        return toExternalForm();
    }

    public HeaderElement[] getValues() throws HttpException {
        return HeaderElement.parse(getValue());
    }

    public HeaderElement[] getElements() {
        return HeaderElement.parseElements(getValue());
    }

    public boolean isAutogenerated() {
        return this.isAutogenerated;
    }
}
