package rocon_service_pair_msgs;

import org.ros.internal.message.Message;
import uuid_msgs.UniqueID;

public interface TestiesResponse extends Message {
    public static final String _DEFINITION = "# ====== DO NOT MODIFY! AUTOGENERATED FROM A SERVICE PAIR DEFINITION ======\nuuid_msgs/UniqueID id\nstring data\n";
    public static final String _TYPE = "rocon_service_pair_msgs/TestiesResponse";

    String getData();

    UniqueID getId();

    void setData(String str);

    void setId(UniqueID uniqueID);
}
