package tf2_msgs;

import org.ros.internal.message.Message;

public interface LookupTransformFeedback extends Message {
    public static final String _DEFINITION = "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n#feedback definition\n";
    public static final String _TYPE = "tf2_msgs/LookupTransformFeedback";
}
