package tf2_msgs;

import org.ros.internal.message.Message;

public interface LookupTransformAction extends Message {
    public static final String _DEFINITION = "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\nLookupTransformActionGoal action_goal\nLookupTransformActionResult action_result\nLookupTransformActionFeedback action_feedback\n";
    public static final String _TYPE = "tf2_msgs/LookupTransformAction";

    LookupTransformActionFeedback getActionFeedback();

    LookupTransformActionGoal getActionGoal();

    LookupTransformActionResult getActionResult();

    void setActionFeedback(LookupTransformActionFeedback lookupTransformActionFeedback);

    void setActionGoal(LookupTransformActionGoal lookupTransformActionGoal);

    void setActionResult(LookupTransformActionResult lookupTransformActionResult);
}
