package tf2_msgs;

import org.ros.internal.message.Message;

public interface LookupTransformResult extends Message {
    public static final String _DEFINITION = "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n#result definitiongeometry_msgs/TransformStamped transform\ntf2_msgs/TF2Error error\n";
    public static final String _TYPE = "tf2_msgs/LookupTransformResult";

    TF2Error getError();

    void setError(TF2Error tF2Error);
}
